spring.application.name=carrental
server.port=9090
storefront.urls.searchcar=http://localhost:8080/car/all
storefront.urls.returncar=http://localhost:8080/returncar
storefront.urls.ordercar=http://localhost:8080/order/edit